### ISSUE TITLE
Current results in the same time units

### ISSUE THREAD

**Issue by zeenix** [KillingSpark/rust-dbus-comparisons#11]
I think it'd be much easier to read the tables if at least the same columns were in the same unit. I had missed the "ms" and thought they're super fast. :-D

https://github.com/KillingSpark/rust-dbus-comparisons/blob/master/Readme.md#current-results

**Comment by KillingSpark** [comment]
I should just write a small script to parse the output of the benchmarks. Currently I do it by hand and its annoying enough to copy paste that. I think I would just make more conversion errors if I did the conversin by hand too :D

**Comment by KillingSpark** [comment]
Eh I did it while rebenchmarking. It's not that hard, turns out I am able to move a period three digits to the right :D
