### ISSUE TITLE
make_dbusrs_message marshals parts.dict twice instead of once like in all other cases

### ISSUE THREAD

**Issue by KillingSpark** [KillingSpark/rust-dbus-comparisons#4]
make_dbusrs_message marshals parts.dict twice instead of once like in all other cases. Needs a fix and re-benchmarking for the readme

**Comment by diwic** [comment]
Noticed that too, fixed in https://github.com/KillingSpark/rust-dbus-comparisons/pull/6

**Comment by KillingSpark** [comment]
Merged #6, thanks for the fix! Rebenchmarking will be done in a few days, I will update the readme then :)

**Comment by KillingSpark** [comment]
Benchmarking has been done. Closing since the original issue has been fixed with #6.
