### ISSUE TITLE
Vec creation shouldn't count against zvariant

### ISSUE THREAD

**Issue by zeenix** [KillingSpark/rust-dbus-comparisons#8]
I just realized something. The Vec creation time here:

https://github.com/KillingSpark/rust-dbus-comparisons/blob/master/benches/marshal_bench.rs#L357

will count against zvariant's encoding time and I think it shouldn't. The new (serde-based) API allows you to serialize your typical data types directly and hence creation of the DS shouldn't be counted against zvariant/zbus.

Oh and btw, we removed those println statements so you can totally send your zbus message now. However, sending is just sending the already encoded bytes on a socket directly so don't think that should count against zbus either.

**Comment by KillingSpark** [comment]
I think it is a common pattern to use special transmission structs that do not get used elsewhere in the code, and not have the serde derives directly on the structs used in the rest of the program directly. So you would pay the creation cost in some form or another right?

There might be a difference in how efficiently the "just sending the bytes on a socket" is implemented. Theoretically, if your encoding/decoding would be very fast but your sending logic would be very slow, in the end your library would not be really useful. So including this in the benchmarks is somewhat relevant I think.

**Comment by KillingSpark** [comment]
Also doing a quick bench, vec creation takes ~450ns for the mixed case and ~30ns for the other two benches. This might be scientifically signifcant but does not change the bigger picture.

**Comment by KillingSpark** [comment]
Btw, this code currently does not compile for me. Maybe cargo picks up the wrong versions? On which commits/tags should I point the zbus/zvariant dependency?

**Comment by zeenix** [comment]
>  think it is a common pattern to use special transmission structs that do not get used elsewhere in the code, and not have the serde derives directly on the structs used in the rest of the program directly. So you would pay the creation cost in some form or another right?

It all depends but usually you would create your structs so that they can be directly serialized, especially if you'd be sending huge amounts of them across.

> There might be a difference in how efficiently the "just sending the bytes on a socket" is implemented. Theoretically, if your encoding/decoding would be very fast but your sending logic would be very slow, in the end your library would not be really useful. So including this in the benchmarks is somewhat relevant I think.

Correct but I was just saying that in case of zbus, it's only sending the encoded bytes on the socket and encoding/serialization already takes place during Message creation.

> Btw, this code currently does not compile for me. Maybe cargo picks up the wrong versions? On which commits/tags should I point the zbus/zvariant dependency?

Oh it seems I forgot to add:

```diff
-zvariant = {git = "https://gitlab.freedesktop.org/zeenix/zbus", version = "^2"}
+zvariant = "^2"
```

to the Cargo.toml. Can you try with that?

**Comment by zeenix** [comment]
> to the Cargo.toml. Can you try with that?

Actually that shouldn't be needed but I'm guessing an older commit of zvariant is cached by cargo and api changed since. You could also try `cargo clean`.

**Comment by KillingSpark** [comment]
I had an old commit in Cargo.lock. Fixed it :)

> It all depends but usually you would create your structs so that they can be directly serialized, especially if you'd be sending huge amounts of them across.

If you are able to use the derives instead I would accept a PR of this version too. Maybe make a second function zvariant_derived so it can be compared to the current version? Then both usecases would be covered, right?

> Correct but I was just saying that in case of zbus, it's only sending the encoded bytes on the socket and encoding/serialization already takes place during Message creation.

Yeah but I think its valuable to have a picture of how the whole workflow of a library compares.

**Comment by zeenix** [comment]
> I had an old commit in Cargo.lock. Fixed it :)

:+1: 

> If you are able to use the derives instead I would accept a PR of this version too. Maybe make a second function zvariant_derived so it can be compared to the current version? Then both usecases would be covered, right?

Sure thing! but the structure creation will have to be in `run_marshal_benches` then?

**Comment by KillingSpark** [comment]
Yep. Maybe make a helper function that takes a MessageParts and creates the appropriate struct. Then pass that struct to the zvariant_derived benchmark
